### PR TITLE
Release v1.1.0

### PR DESCRIPTION
**Pull request by albertochimentiinbibo**
Release of the documentation corresponding to Shift 1.1.0 version.

This includes changes to:

- Updated Shift UI with new threaded workflow feature details
- Updated Basics/Execute sections with new threaded workflow feature details and gifs
- Updated Integration and Resources section for Nuke with new Shift tools setup and ShiftWorkflow node description
- Updated Creative Software catalog OBJImport node documentation
- Updated Standard catalog PythonScript node documentation
- Updated Developer Guide with details on threaded execution decorator and wrapper use

### CODE REVIEW

**Review by juliavisserinbibo — COMMENTED** [review]
At the moment the side menu for the release notes in the preview tool looks like this:
image

Titles seem to not be tabulated properly. If once is up the problem persists, we might have to contact Carlos or the website guys to see if it's a problem on our end. 

On the Adonis documentation this menu looks like this
image

**Comment by mromeoinbibo** [comment]
> At the moment the side menu for the release notes in the preview tool looks like this: image
> 
> Titles seem to not be tabulated properly. If once is up the problem persists, we might have to contact Carlos or the website guys to see if it's a problem on our end.
> 
> On the Adonis documentation this menu looks like this image

I would say this is not a blocker towards releasing the docs.

**Comment by juliavisserinbibo** [comment]
> At the moment the side menu for the release notes in the preview tool looks like this: image
> 
> Titles seem to not be tabulated properly. If once is up the problem persists, we might have to contact Carlos or the website guys to see if it's a problem on our end.
> 
> On the Adonis documentation this menu looks like this image



> At the moment the side menu for the release notes in the preview tool looks like this: image
> 
> Titles seem to not be tabulated properly. If once is up the problem persists, we might have to contact Carlos or the website guys to see if it's a problem on our end.
> 
> On the Adonis documentation this menu looks like this image

The main difference I see is that in our release notes we use line separators between the release notes version. We might want to test removing them before merging into main? As a Hotfix

**Comment by mromeoinbibo** [comment]
> > At the moment the side menu for the release notes in the preview tool looks like this: image
> > Titles seem to not be tabulated properly. If once is up the problem persists, we might have to contact Carlos or the website guys to see if it's a problem on our end.
> > On the Adonis documentation this menu looks like this image
> 
> > At the moment the side menu for the release notes in the preview tool looks like this: image
> > Titles seem to not be tabulated properly. If once is up the problem persists, we might have to contact Carlos or the website guys to see if it's a problem on our end.
> > On the Adonis documentation this menu looks like this image
> 
> The main difference I see is that in our release notes we use line separators between the release notes version. We might want to test removing them before merging into main? As a Hotfix

@albertochimentiinbibo could you try Julia's suggestion?

**Comment by albertochimentiinbibo** [comment]
Now looks good
@mromeoinbibo @juliavisserinbibo 
image

**Review by mromeoinbibo — APPROVED** [review]

**Review by juliavisserinbibo — APPROVED** [review]

**Pull request merged**
